export const IPC_CHANNELS = {
  BOOKMARK_LIST: 'bookmark:list',
  BOOKMARK_GET: 'bookmark:get',
  BOOKMARK_CREATE: 'bookmark:create',
  BOOKMARK_UPDATE: 'bookmark:update',
  BOOKMARK_DELETE: 'bookmark:delete',
  BOOKMARK_SEARCH: 'bookmark:search',
  IMPORT_HTML: 'import:html',
  IMPORT_PREVIEW: 'import:preview',
  IMPORT_EXECUTE: 'import:execute',
  TAG_LIST: 'tag:list',
  TAG_ADD_BOOKMARK: 'tag:addBookmark',
  TAG_REMOVE_BOOKMARK: 'tag:removeBookmark',
  DUPLICATE_FIND: 'duplicate:find',
  DUPLICATE_MERGE: 'duplicate:merge',
  SYNC_STATUS: 'sync:status',
  SYNC_RUN: 'sync:run',
  SYNC_SET_CONFIG: 'sync:setConfig',
  SYNC_CLEAR_CONFIG: 'sync:clearConfig',
  SYNC_TEST: 'sync:test',
  CONFLICT_RESOLVE: 'conflict:resolve',
  CONFLICT_APPLY_MERGE: 'conflict:applyMerge',
  AI_SERVER_START: 'ai:serverStart',
  AI_SERVER_STOP: 'ai:serverStop',
  AI_SERVER_STATUS: 'ai:serverStatus',
} as const
